name: Deploy VPS
on: [push]
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: pull changes to vps
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /Projects/github-action-example
            git pull origin main
